numero1 = int(input("Introduce el primer numero: "))
numero2 = int(input("Introduce el segundo numero: "))
numero3 = int(input("Introduce el tercer numero: "))
print("El numero mas alto es: {}".format(max(numero1, numero2, numero3)))
print("El numero mas pequeño es: {}".format(min(numero1, numero2, numero3)))