/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import calculadoraareavolumen.cubo;
import javax.swing.ImageIcon;

/**
 *
 * @author arque
 */
public class cuadradoFrame extends javax.swing.JFrame {

    /**
     * Creates new form esferaFrame
     */
    public cuadradoFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        ImageIcon icono = new ImageIcon("src/imagenes/cubo.png");
        this.setIconImage(icono.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiquetaAlto = new javax.swing.JLabel();
        etiquetaAncho = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        campoTextoAlto = new javax.swing.JTextField();
        campoTextoProfundidad = new javax.swing.JTextField();
        campoTextoAncho = new javax.swing.JTextField();
        imagenCuadrado = new javax.swing.JLabel();
        botonAreaCubo = new javax.swing.JButton();
        botonVolumenCubo = new javax.swing.JButton();
        etiquetaTituloRes = new javax.swing.JLabel();
        Resultado = new javax.swing.JLabel();
        botonVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CUBO");
        setIconImage(getIconImage());
        setIconImages(getIconImages());
        setName("Cuadrado"); // NOI18N
        setResizable(false);

        etiquetaAlto.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        etiquetaAlto.setText("Alto:");

        etiquetaAncho.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        etiquetaAncho.setText("Ancho: ");

        jLabel3.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel3.setText("Profundidad: ");

        campoTextoAlto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoTextoAlto.setText("0");
        campoTextoAlto.setToolTipText("valor");

        campoTextoProfundidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoTextoProfundidad.setText("0");
        campoTextoProfundidad.setToolTipText("valor");

        campoTextoAncho.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoTextoAncho.setText("0");
        campoTextoAncho.setToolTipText("valor");

        imagenCuadrado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cubo.png"))); // NOI18N

        botonAreaCubo.setText("Area");
        botonAreaCubo.setBorderPainted(false);
        botonAreaCubo.setContentAreaFilled(false);
        botonAreaCubo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonAreaCubo.setFocusable(false);
        botonAreaCubo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAreaCuboActionPerformed(evt);
            }
        });

        botonVolumenCubo.setText("Volumen");
        botonVolumenCubo.setBorderPainted(false);
        botonVolumenCubo.setContentAreaFilled(false);
        botonVolumenCubo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonVolumenCubo.setFocusable(false);
        botonVolumenCubo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolumenCuboActionPerformed(evt);
            }
        });

        etiquetaTituloRes.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        etiquetaTituloRes.setText("Resultado:");

        Resultado.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        Resultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Resultado.setText("0");

        botonVolver.setText("Volver");
        botonVolver.setActionCommand("");
        botonVolver.setBorderPainted(false);
        botonVolver.setContentAreaFilled(false);
        botonVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonVolver.setFocusable(false);
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(etiquetaAlto, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(etiquetaAncho)
                    .addComponent(etiquetaTituloRes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoTextoProfundidad, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoTextoAlto, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoTextoAncho, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Resultado, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(botonAreaCubo, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(botonVolumenCubo)
                        .addComponent(imagenCuadrado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(botonVolver))
                .addGap(13, 13, 13))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(etiquetaAlto, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoTextoAlto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(etiquetaAncho, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoTextoAncho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(imagenCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoTextoProfundidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(etiquetaTituloRes)
                            .addComponent(Resultado))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonAreaCubo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonVolumenCubo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonVolver)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAreaCuboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAreaCuboActionPerformed
        double altura = Double.parseDouble(campoTextoAlto.getText());
        double ancho = Double.parseDouble(campoTextoAncho.getText());
        double profundidad = Double.parseDouble(campoTextoProfundidad.getText());
        cubo cubo1 = new cubo(altura, ancho, profundidad);
        Resultado.setText(String.format("%.2f", cubo1.area())+ " m^2");
    }//GEN-LAST:event_botonAreaCuboActionPerformed

    private void botonVolumenCuboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolumenCuboActionPerformed
        double altura = Double.parseDouble(campoTextoAlto.getText());
        double ancho = Double.parseDouble(campoTextoAncho.getText());
        double profundidad = Double.parseDouble(campoTextoProfundidad.getText());
        cubo cubo1 = new cubo(altura, ancho, profundidad);
        Resultado.setText(String.format("%.2f", cubo1.volumen()) + " m^3");
    }//GEN-LAST:event_botonVolumenCuboActionPerformed

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        Menu ventana = new Menu();
        ventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cuadradoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cuadradoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cuadradoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cuadradoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cuadradoFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Resultado;
    private javax.swing.JButton botonAreaCubo;
    private javax.swing.JButton botonVolumenCubo;
    private javax.swing.JButton botonVolver;
    private javax.swing.JTextField campoTextoAlto;
    private javax.swing.JTextField campoTextoAncho;
    private javax.swing.JTextField campoTextoProfundidad;
    private javax.swing.JLabel etiquetaAlto;
    private javax.swing.JLabel etiquetaAncho;
    private javax.swing.JLabel etiquetaTituloRes;
    private javax.swing.JLabel imagenCuadrado;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
