/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import calculadoraareavolumen.*;

import javax.swing.ImageIcon;

/**
 *
 * @author arque
 */
public class cilindroFrame extends javax.swing.JFrame {

    /**
     * Creates new form esferaFrame
     */
    public cilindroFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        ImageIcon icono = new ImageIcon("src/imagenes/cilindro.png");
        this.setIconImage(icono.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiquetaAlto = new javax.swing.JLabel();
        etiquetaRadio = new javax.swing.JLabel();
        campoTextoAlto = new javax.swing.JTextField();
        campoTextoRadio = new javax.swing.JTextField();
        imagenCilindo = new javax.swing.JLabel();
        botonAreaCubo = new javax.swing.JButton();
        botonVolumenCubo = new javax.swing.JButton();
        etiquetaTituloRes = new javax.swing.JLabel();
        Resultado = new javax.swing.JLabel();
        botonVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CILINDRO");
        setIconImage(getIconImage());
        setIconImages(getIconImages());
        setName("Cuadrado"); // NOI18N
        setResizable(false);

        etiquetaAlto.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        etiquetaAlto.setText("Alto:");

        etiquetaRadio.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        etiquetaRadio.setText("Radio: ");

        campoTextoAlto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoTextoAlto.setText("0");
        campoTextoAlto.setToolTipText("valor");

        campoTextoRadio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoTextoRadio.setText("0");
        campoTextoRadio.setToolTipText("valor");

        imagenCilindo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cilindro.png"))); // NOI18N

        botonAreaCubo.setText("Area");
        botonAreaCubo.setBorderPainted(false);
        botonAreaCubo.setContentAreaFilled(false);
        botonAreaCubo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonAreaCubo.setFocusable(false);
        botonAreaCubo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAreaCuboActionPerformed(evt);
            }
        });

        botonVolumenCubo.setText("Volumen");
        botonVolumenCubo.setBorderPainted(false);
        botonVolumenCubo.setContentAreaFilled(false);
        botonVolumenCubo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonVolumenCubo.setFocusable(false);
        botonVolumenCubo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolumenCuboActionPerformed(evt);
            }
        });

        etiquetaTituloRes.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        etiquetaTituloRes.setText("Resultado:");

        Resultado.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        Resultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Resultado.setText("0");

        botonVolver.setText("Volver");
        botonVolver.setActionCommand("");
        botonVolver.setBorderPainted(false);
        botonVolver.setContentAreaFilled(false);
        botonVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonVolver.setFocusable(false);
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(etiquetaAlto, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaRadio)
                    .addComponent(etiquetaTituloRes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoTextoAlto, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoTextoRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Resultado, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonVolver)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(botonAreaCubo, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(botonVolumenCubo)
                        .addComponent(imagenCilindo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(etiquetaAlto, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoTextoAlto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(etiquetaRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoTextoRadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(imagenCilindo, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(etiquetaTituloRes)
                            .addComponent(Resultado)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonAreaCubo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonVolumenCubo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonVolver)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAreaCuboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAreaCuboActionPerformed
        double radio = Double.parseDouble(campoTextoRadio.getText());
        double altura = Double.parseDouble(campoTextoAlto.getText());
       
        cilindro cilindro1 = new cilindro(radio , altura );
        Resultado.setText(String.format("%.2f", cilindro1.area()) + " m^2");
    }//GEN-LAST:event_botonAreaCuboActionPerformed

    private void botonVolumenCuboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolumenCuboActionPerformed
        double radio = Double.parseDouble(campoTextoRadio.getText());
        double altura = Double.parseDouble(campoTextoAlto.getText());
       
        cilindro cilindro1 = new cilindro(radio , altura );
        Resultado.setText(String.format("%.2f", cilindro1.volumen()) + " m^3");
    }//GEN-LAST:event_botonVolumenCuboActionPerformed

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
       Menu ventana = new Menu();
       ventana.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_botonVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cilindroFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cilindroFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cilindroFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cilindroFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cilindroFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Resultado;
    private javax.swing.JButton botonAreaCubo;
    private javax.swing.JButton botonVolumenCubo;
    private javax.swing.JButton botonVolver;
    private javax.swing.JTextField campoTextoAlto;
    private javax.swing.JTextField campoTextoRadio;
    private javax.swing.JLabel etiquetaAlto;
    private javax.swing.JLabel etiquetaRadio;
    private javax.swing.JLabel etiquetaTituloRes;
    private javax.swing.JLabel imagenCilindo;
    // End of variables declaration//GEN-END:variables
}
